import type { AppLanguage } from "../SettingsProvider/settings.types";

export type TranslationValue =
  | string
  | {
      [key: string]: TranslationValue;
    };

export type TranslationDictionary = {
  [key: string]: TranslationValue;
};

export type TranslationKey =
  | "navigation.today"
  | "navigation.progress"
  | "navigation.ask"
  | "navigation.goals"
  | "navigation.profile"
  | "today.header.eyebrow"
  | "today.header.title"
  | "today.header.subtitle"
  | "today.condition.title"
  | "today.condition.description"
  | "today.dailyBrief.title"
  | "today.dailyBrief.subtitle"
  | "today.dailyBrief.recommendationLabel"
  | "today.upcomingWorkout.title"
  | "today.upcomingWorkout.subtitle"
  | "today.upcomingWorkout.detailsAriaLabel"
  | "today.metrics.sleep"
  | "today.metrics.restingHeartRate"
  | "today.metrics.recovery"
  | "today.metrics.trainingLoad"
  | "today.recoveryTrend.title"
  | "today.recoveryTrend.subtitle"
  | "today.recoveryTrend.chartAriaLabel"
  | "today.recommendation.title"
  | "today.recommendation.subtitle"
  | "today.recentActivity.title"
  | "today.recentActivity.subtitle"
  | "progress.header.eyebrow"
  | "progress.header.title"
  | "progress.header.subtitle"
  | "progress.weeklySummary.title"
  | "progress.weeklySummary.subtitle"
  | "progress.trainingLoad.title"
  | "progress.trainingLoad.subtitle"
  | "progress.trainingLoad.chartAriaLabel"
  | "progress.metrics.consistency"
  | "progress.metrics.recovery"
  | "progress.goal.title"
  | "progress.goal.subtitle"
  | "progress.goal.currentLabel"
  | "progress.goal.targetLabel"
  | "progress.recentAchievement.title"
  | "progress.recentAchievement.subtitle"
  | "progress.trainingLoad.points.week1"
  | "progress.trainingLoad.points.week2"
  | "progress.trainingLoad.points.week3"
  | "progress.trainingLoad.points.week4"
  | "progress.trainingLoad.points.week5"
  | "progress.trainingLoad.points.week6"
  | "progress.trainingLoad.points.now"
  | "goals.header.eyebrow"
  | "goals.header.title"
  | "goals.header.subtitle"
  | "goals.primaryGoal.title"
  | "goals.primaryGoal.subtitle"
  | "goals.supportingGoals.sectionTitle"
  | "goals.supportingGoals.sectionDescription"
  | "goals.supportingGoals.cardTitle"
  | "goals.supportingGoals.cardSubtitle"
  | "goals.goal.currentLabel"
  | "goals.goal.targetLabel"
  | "goals.recommendation.title"
  | "goals.recommendation.subtitle"
  | "ask.preview.title"
  | "ask.preview.subtitle"
  | "ask.preview.description"
  | "profile.header.eyebrow"
  | "profile.header.title"
  | "profile.header.subtitle"
  | "profile.cards.personal"
  | "profile.cards.training"
  | "profile.cards.devices"
  | "profile.cards.settings"
  | "profile.cards.personalInformation"
  | "profile.cards.trainingPreferences"
  | "profile.cards.connectedDevices"
  | "profile.cards.dataSources"
  | "profile.cards.applicationSettings"
  | "profile.cards.preferences"
  | "profile.personal.age"
  | "profile.personal.height"
  | "profile.personal.weight"
  | "profile.personal.location"
  | "profile.training.primarySport"
  | "profile.training.weeklyTarget"
  | "profile.training.longRunDay"
  | "profile.training.restDay"
  | "profile.training.preferredTrainingTime"
  | "profile.devices.connected"
  | "profile.devices.disconnected"
  | "profile.devices.lastSync"
  | "profile.devices.subtitle"
  | "profile.settings.units"
  | "profile.settings.language"
  | "profile.settings.theme"
  | "profile.settings.units.label"
  | "profile.settings.units.description"
  | "profile.settings.language.label"
  | "profile.settings.language.description"
  | "profile.settings.theme.label"
  | "profile.settings.theme.description"
  | "profile.settings.options.system"
  | "profile.settings.options.light"
  | "profile.settings.options.dark"
  | "profile.settings.options.english"
  | "profile.settings.options.russian"
  | "profile.settings.preferences"
  | "profile.settings.soon"
  | "profile.devices.status.connected"
  | "profile.devices.status.disconnected";

export type LocalizationContextValue = {
  language: AppLanguage;
  t: (key: TranslationKey) => string;
};
